import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import TanstackQueryProvider from "@/providers/tanstack/TanstackQueryProvider";
import ReduxProvider from "@/providers/ReduxProvider";
import AuthInit from "@/providers/AuthInit";


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "TSM TYCTH",
  description: "Generated by create next app",
    icons : '/icon.png',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <ReduxProvider>
          <AuthInit/>
      <TanstackQueryProvider>
        {children}
      </TanstackQueryProvider>
      </ReduxProvider>
      </body>
    </html>
  );
}